### ISSUE TITLE
error

### ISSUE THREAD

**Issue by desiwantrina** [oneall/social-login-opencart#2]
i'm newbie in opencart 
i already installed the oneall in opencart, and when i go to module>>one all setting and i want to add "facebook" login, nothing happens. and there is an error in 
Parse error: syntax error, unexpected end of file in C:\xampp\htdocs\opencart\upload\catalog\view\theme\default \template\module\oneall.tpl on line 75

**Comment by SchlesserClaude** [comment]
Hello, thank you for the bug report. We will have a look at it immediately. In the meantime, please download the extensions here: http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24825

**Comment by ghost** [comment]
Hi,
Where did you install the OpenCart module from? 
This github.com repo, or the opencart.com repo (as mentioned in Claude's answer)?

Thanks.
